import React, { useEffect, useRef, useState } from 'react'
import {
    getTherapyRationale, getCohortKM,
    TherapyRationaleResponse, TreatmentKMEvidence, ReferenceKMCurve,
} from '../../services/api'
import KaplanMeierChart from '../KaplanMeierChart'
import { classifyDrugCurve, topTreatmentCurves } from '../../utils/signatureViz'
import { RuoNotice } from '../ui'

interface TherapyDirectionsProps {
    modelId: string
    riskGroup?: string | null
    genes?: string[]
    /** The patient's own predicted curve (from the base model) — overlaid on the
     *  treatment comparison chart as a reference line so each drug's cohort
     *  outcome is directly comparable against the patient's current predicted
     *  trajectory. */
    baselineCurve?: ReferenceKMCurve | null
    /** The patient's scored tumour profile — sent so each drug's cohort-reference
     *  curve is picked by scoring the patient against THAT treatment-specific
     *  model, instead of reusing `riskGroup` (a different model's tertile
     *  label) as a match key. Never persisted server-side. */
    expression?: Record<string, number>
    clinical?: Record<string, string>
    /** Baseline model's survival-time unit, so the comparison chart's axis
     *  matches the (numerically dominant) baseline curve instead of always
     *  defaulting to days. */
    timeUnit?: string
    /** Fire generate() once on mount instead of waiting for the button — used
     *  when the clinical console's show_treatment_evidence action opens this
     *  panel directly in response to a question. */
    autoGenerate?: boolean
}

const POLL_INTERVAL_MS = 15_000
const POLL_TIMEOUT_MS = 10 * 60_000
const PRESET_TOP_N = [5, 10]
const DEFAULT_TOP_N = 5
// Mirrors backend `_MAX_COHORT_KM_DRUGS` — the generate() call auto-resolves
// this many; requesting a batch of MORE is capped the same way server-side, so
// keep on-demand "check more" requests within one call's worth at a time.
const COHORT_KM_BATCH = 8

/**
 * Grounded "treatments to consider" (Oncologist Mode). On demand, the AI writes
 * advisory suggestions over REAL CIViC/DGIdb evidence for the risk-driving genes —
 * advisory, not a prescription. The cited associations are always shown alongside
 * the prose.
 *
 * The chart/table selection is driven by `ranked_drugs` from the backend — the
 * SAME round-robin-across-genes + evidence-level ranking used to decide which
 * drugs get an eager cohort-KM lookup at generate() time, with documented
 * CIViC resistance/adverse-outcome rows already excluded (see
 * `_rank_drugs_by_gene_priority` in chat_routes.py). N adjustable via the
 * control above the chart. Only the first `COHORT_KM_BATCH` drugs are
 * auto-resolved; raising N past that surfaces an explicit "check more" action
 * rather than firing background builds the user didn't ask to see. The table
 * below the chart is filtered to the same N drugs so plot and table always
 * describe the same data; any drug excluded from ranking for documented
 * resistance/adverse evidence is still disclosed separately, unplotted.
 */
const TherapyDirections: React.FC<TherapyDirectionsProps> = ({
    modelId, riskGroup, genes, baselineCurve, expression, clinical, timeUnit = 'days', autoGenerate = false,
}) => {
    const [data, setData] = useState<TherapyRationaleResponse | null>(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [cohortKm, setCohortKm] = useState<Record<string, TreatmentKMEvidence>>({})
    const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null)
    const pollStartRef = useRef<number | null>(null)
    const [topN, setTopN] = useState<number | 'all'>(DEFAULT_TOP_N)
    const [checkingMore, setCheckingMore] = useState(false)
    const [pollTimedOut, setPollTimedOut] = useState(false)
    const autoGeneratedRef = useRef(false)

    useEffect(() => () => {
        if (pollRef.current) clearTimeout(pollRef.current)
    }, [])

    useEffect(() => {
        if (autoGenerate && !autoGeneratedRef.current) {
            autoGeneratedRef.current = true
            void generate()
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [autoGenerate])

    const mergeCohortKm = (results: TreatmentKMEvidence[]) => {
        setCohortKm((prev) => {
            const next = { ...prev }
            for (const r of results) next[r.drug.toLowerCase()] = r
            return next
        })
        return results.filter((r) => r.is_building).map((r) => r.drug)
    }

    const pollCohortKm = async (drugs: string[]) => {
        if (drugs.length === 0) return
        try {
            const results = await getCohortKM({ modelId, drugs, expression, clinical })
            const stillBuilding = mergeCohortKm(results)
            if (stillBuilding.length === 0) {
                pollStartRef.current = null
                return
            }
            const elapsed = Date.now() - (pollStartRef.current ?? Date.now())
            if (elapsed > POLL_TIMEOUT_MS) {
                pollStartRef.current = null
                setPollTimedOut(true)
                return
            }
            pollRef.current = setTimeout(() => pollCohortKm(stillBuilding), POLL_INTERVAL_MS)
        } catch {
            // Network hiccup — stop polling silently; Regenerate will retry.
        }
    }

    const generate = async () => {
        setLoading(true)
        setError(null)
        setPollTimedOut(false)
        if (pollRef.current) {
            clearTimeout(pollRef.current)
            pollRef.current = null
        }

        try {
            const r = await getTherapyRationale({ modelId, riskGroup, genes, expression, clinical })
            setData(r)

            const initial: Record<string, TreatmentKMEvidence> = {}
            const building: string[] = []
            for (const e of r.evidence) {
                if (e.cohort_km) {
                    initial[e.drug.toLowerCase()] = e.cohort_km
                    if (e.cohort_km.is_building) building.push(e.cohort_km.drug)
                }
            }
            setCohortKm(initial)
            if (building.length > 0) {
                pollStartRef.current = Date.now()
                pollRef.current = setTimeout(() => pollCohortKm(building), POLL_INTERVAL_MS)
            }
        } catch (err) {
            const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
            setError(detail ?? 'Could not generate therapeutic directions.')
        } finally {
            setLoading(false)
        }
    }

    const hasGenerated = data !== null || loading || error !== null
    const rankedDrugs = data?.ranked_drugs ?? []

    // "Show top N" ranks by clinical priority, not data availability — a drug
    // confirmed to have no GEO cohort data still burns one of the N slots.
    // Backfill it with the next-ranked drug beyond the window that's already
    // confirmed plottable (from data fetched eagerly at generate() time, no
    // new network calls here), so N means N real curves whenever possible.
    // Scope is limited to `unavailable` — `insufficient`/`not_checked`/
    // `building` stay as-is (ambiguous or pending, not a confirmed dead end).
    const classify = (d: string) => classifyDrugCurve(d, cohortKm, riskGroup ?? null)
    const windowDrugs = topN === 'all' ? rankedDrugs : rankedDrugs.slice(0, topN)
    const bumpedUnavailable = windowDrugs.filter((d) => classify(d) === 'unavailable')

    let displayedDrugs = windowDrugs
    if (topN !== 'all' && bumpedUnavailable.length > 0) {
        const kept = windowDrugs.filter((d) => classify(d) !== 'unavailable')
        const overflowPlottable = rankedDrugs.slice(topN).filter((d) => classify(d) === 'plottable')
        const fill = overflowPlottable.slice(0, bumpedUnavailable.length)
        const finalSet = new Set([...kept, ...fill])
        displayedDrugs = rankedDrugs.filter((d) => finalSet.has(d)) // preserve rank order
    }
    const displayedDrugKeys = new Set(displayedDrugs.map((d) => d.toLowerCase()))

    const { curves, insufficientN, needsPatientProfile, horizonYears, baselineOmittedReason } = topTreatmentCurves(
        displayedDrugs, cohortKm, riskGroup ?? null, baselineCurve, timeUnit,
    )
    const chartedDrugKeys = new Set(curves.filter((c) => c.key !== '__baseline').map((c) => c.key.toLowerCase()))
    // Sourced straight from `curves` (not a second index pass) so a table dot
    // can never disagree with its chart line color.
    const drugColor: Record<string, string> = {}
    curves.forEach((c) => { if (c.key !== '__baseline') drugColor[c.key.toLowerCase()] = c.color })

    // A drug-name GEO query frequently returns the same generic cancer dataset
    // no matter which drug was named, so several "different cohort" curves can
    // be the SAME patients — identical lines that look like corroborating
    // evidence but are one cohort counted N times. Disclose it rather than
    // letting the chart imply independent replication.
    const sharedCohorts = (() => {
        const byAccession: Record<string, string[]> = {}
        for (const d of displayedDrugs) {
            const km = cohortKm[d.toLowerCase()]
            if (km?.tier === 'cohort_reference' && km.accession) {
                ;(byAccession[km.accession] ??= []).push(d)
            }
        }
        return Object.entries(byAccession).filter(([, ds]) => ds.length > 1)
    })()

    const buildingDrugs = displayedDrugs.filter((d) => cohortKm[d.toLowerCase()]?.is_building)
    const notCheckedDrugs = displayedDrugs.filter((d) => cohortKm[d.toLowerCase()]?.tier === 'not_checked')
    // Disclosure reads from the pre-backfill window, not `displayedDrugs` — a
    // drug backfilled out of the visible set must stay disclosed here rather
    // than silently disappearing.
    const unavailableDrugs = bumpedUnavailable

    // Evidence rows for a drug that never entered `ranked_drugs` at all — i.e.
    // every row for that drug carried documented CIViC resistance/adverse
    // significance. Kept visible here (never plotted) so that evidence isn't
    // silently dropped from the page.
    const excludedEvidence = data
        ? data.evidence.filter((e) => !rankedDrugs.some((d) => d.toLowerCase() === e.drug.toLowerCase()))
        : []

    const checkMoreDrugs = async () => {
        const batch = notCheckedDrugs.slice(0, COHORT_KM_BATCH)
        if (batch.length === 0) return
        setCheckingMore(true)
        setPollTimedOut(false)
        try {
            const results = await getCohortKM({ modelId, drugs: batch, expression, clinical })
            const stillBuilding = mergeCohortKm(results)
            if (stillBuilding.length > 0) {
                pollStartRef.current = Date.now()
                pollRef.current = setTimeout(() => pollCohortKm(stillBuilding), POLL_INTERVAL_MS)
            }
        } catch {
            // Best-effort — the button stays visible so the user can retry.
        } finally {
            setCheckingMore(false)
        }
    }

    return (
        <div className="border border-alt-border rounded-lg p-4 bg-alt-soft">
            <div className="flex items-center justify-between gap-3 mb-2">
                <h3 className="font-semibold text-fg-strong">Treatments to consider</h3>
                <button
                    onClick={generate}
                    disabled={loading}
                    className="px-3 py-1.5 text-sm bg-alt text-on-accent rounded hover:bg-alt-hover disabled:opacity-50"
                >
                    {loading ? 'Generating…' : data ? 'Regenerate' : 'Generate'}
                </button>
            </div>

            <RuoNotice scope="treatment" text={data?.disclaimer} className="mb-3 font-semibold" />

            {!hasGenerated && (
                <p className="text-sm text-fg-muted">
                    Surface documented CIViC/DGIdb drug–biomarker associations for this patient's
                    risk-driving genes, with real GEO cohort survival curves for the top matched drugs and
                    an AI-written summary framed as research hypotheses.
                </p>
            )}

            {error && (
                <div className="text-sm text-danger bg-danger-soft border border-danger-border rounded p-2">{error}</div>
            )}

            {data && (
                <div className="space-y-3">
                    <p className="text-sm text-fg whitespace-pre-line">{data.rationale}</p>

                    {data.evidence.length > 0 && (
                        <div className="border border-border rounded-lg p-3 bg-surface">
                            <div className="flex items-center justify-between gap-3 mb-1 flex-wrap">
                                <h4 className="text-sm font-semibold text-fg">Treatment outcome comparison</h4>
                                <div className="flex items-center gap-1.5 text-xs">
                                    <span className="text-fg-muted">Show top</span>
                                    {PRESET_TOP_N.map((n) => (
                                        <button
                                            key={n}
                                            onClick={() => setTopN(n)}
                                            className={`px-2 py-0.5 rounded border ${
                                                topN === n
                                                    ? 'bg-alt text-on-accent border-alt'
                                                    : 'bg-surface text-fg-muted border-border-strong hover:bg-surface-sunken'
                                            }`}
                                        >
                                            {n}
                                        </button>
                                    ))}
                                    <button
                                        onClick={() => setTopN('all')}
                                        className={`px-2 py-0.5 rounded border ${
                                            topN === 'all'
                                                ? 'bg-alt text-on-accent border-alt'
                                                : 'bg-surface text-fg-muted border-border-strong hover:bg-surface-sunken'
                                        }`}
                                    >
                                        All ({rankedDrugs.length})
                                    </button>
                                    <input
                                        type="number"
                                        min={1}
                                        max={rankedDrugs.length || 1}
                                        value={typeof topN === 'number' ? topN : rankedDrugs.length}
                                        onChange={(e) => {
                                            const v = Math.round(Number(e.target.value))
                                            if (Number.isFinite(v)) {
                                                setTopN(Math.max(1, Math.min(rankedDrugs.length || 1, v)))
                                            }
                                        }}
                                        className="w-12 border border-border-strong rounded px-1 py-0.5 text-fg"
                                    />
                                </div>
                            </div>
                            <p className="text-[11px] text-fg-muted mb-2">
                                Real GEO cohort survival for the top {displayedDrugs.length} matched drug(s).
                                Where a cohort documents who was and wasn't treated, both arms are drawn as a
                                pair (solid = treated, dashed = its own untreated control) — that within-cohort
                                gap is the only comparison here that speaks to treatment benefit, and it is
                                observational, not randomized. Advisory, not a prescription or a prediction
                                that you will respond.
                            </p>
                            {baselineOmittedReason && (
                                <p className="text-[11px] text-fg-muted bg-surface-sunken border border-border rounded p-2 mb-2">
                                    {baselineOmittedReason}
                                </p>
                            )}
                            {horizonYears > 0 && (
                                <p className="text-[11px] text-fg-muted mb-2">
                                    <strong>Reading this chart:</strong> all cohorts are shown on a common
                                    scale and truncated to {horizonYears < 3 ? horizonYears.toFixed(1) : horizonYears.toFixed(0)} years
                                    — the longest window every plotted cohort actually observed — so a cohort
                                    with longer follow-up doesn't look worse simply for having had more time to
                                    accrue events. Dotted curves come from different patient populations than
                                    your baseline (different stage mix, era and assay), so a gap between them is
                                    <em> not</em> an estimate of what this treatment would do for you.
                                </p>
                            )}

                            {buildingDrugs.length > 0 && !pollTimedOut && (
                                <div className="text-[11px] text-accent-fg bg-accent-soft border border-border-accent rounded p-2 mb-2 flex items-center gap-2">
                                    <div className="w-3 h-3 border-2 border-border-accent border-t-transparent rounded-full animate-spin flex-shrink-0" />
                                    {cohortKm[buildingDrugs[0].toLowerCase()]?.build_stage
                                        ?? `Building cohort models for ${buildingDrugs.join(', ')}… (~2 min each, auto-refreshing)`}
                                </div>
                            )}

                            {buildingDrugs.length > 0 && pollTimedOut && (
                                <div className="text-[11px] text-warn bg-warn-soft border border-warn-border rounded p-2 mb-2">
                                    Still building {buildingDrugs.join(', ')} after 10 minutes — this can happen
                                    with less-common drugs. Click Regenerate to retry, or check back shortly.
                                </div>
                            )}

                            {curves.length > 0 && (
                                <>
                                    {/* Non-dismissible and adjacent to the curve on purpose.
                                        These are observational treated-vs-untreated splits
                                        inside single GEO cohorts — nobody was randomised, so
                                        why a patient did or did not get a drug is unknown and
                                        can fully explain the gap. A reader who sees only the
                                        plot would read a causal effect that is not there. */}
                                    <div className="text-[11px] text-warn bg-warn-soft border border-warn-border rounded p-2 mb-2">
                                        ⚠ <strong>Observational, not randomised.</strong> These curves compare
                                        patients who did and did not receive a treatment within one GEO cohort.
                                        The reasons for that assignment are unknown and may fully explain the
                                        difference (confounding by indication). Hypothesis-generating only —
                                        not evidence that a treatment works.
                                    </div>
                                    {/* `topTreatmentCurves` already normalized every cohort
                                        onto a shared years scale, so the chart renders years
                                        directly rather than re-deriving from a source unit. */}
                                    <KaplanMeierChart curves={curves} height={260} timeUnit="years" />
                                </>
                            )}

                            {curves.length === 0 && buildingDrugs.length === 0 && (
                                <p className="text-[11px] text-fg-faint">
                                    No plottable GEO cohort outcome data yet for the selected drugs.
                                </p>
                            )}

                            {sharedCohorts.length > 0 && (
                                <div className="text-[11px] text-warn bg-warn-soft border border-warn-border rounded p-2 mt-1">
                                    {sharedCohorts.map(([acc, ds]) => (
                                        <div key={acc}>
                                            ⚠ {ds.join(', ')} all resolved to the <strong>same</strong> GEO
                                            series ({acc}) — the same patients, not {ds.length} independent
                                            cohorts. Their curves are identical by construction and say nothing
                                            about how these drugs differ from one another.
                                        </div>
                                    ))}
                                </div>
                            )}

                            {needsPatientProfile.length > 0 && (
                                <p className="text-[11px] text-fg-faint mt-1">
                                    Needs a tumour profile to pick the comparable risk group:{' '}
                                    {needsPatientProfile.join(', ')}. Their evidence is a different cohort's
                                    risk-tertile curve, and without a score there is no basis for choosing
                                    which tertile to show.
                                </p>
                            )}

                            {insufficientN.length > 0 && (
                                <p className="text-[11px] text-fg-faint mt-1">
                                    Not enough matched patients/events to plot reliably: {insufficientN
                                        .map((d) => `${d.drug} (n=${d.nSamples}, ${d.nEvents} events)`)
                                        .join(', ')}.
                                </p>
                            )}

                            {unavailableDrugs.length > 0 && (
                                <p className="text-[11px] text-fg-faint mt-1">
                                    No matching GEO cohort data for: {unavailableDrugs.join(', ')}.
                                </p>
                            )}

                            {notCheckedDrugs.length > 0 && (
                                <div className="mt-2 flex items-center gap-2 text-[11px]">
                                    <span className="text-fg-faint">
                                        Not checked yet for GEO cohort data: {notCheckedDrugs.join(', ')}.
                                    </span>
                                    <button
                                        onClick={checkMoreDrugs}
                                        disabled={checkingMore}
                                        className="px-2 py-0.5 rounded border border-alt-border text-alt bg-alt-soft hover:bg-alt-soft disabled:opacity-50 flex-shrink-0"
                                    >
                                        {checkingMore ? 'Checking…' : `Check ${Math.min(notCheckedDrugs.length, COHORT_KM_BATCH)} more`}
                                    </button>
                                </div>
                            )}

                            <div className="overflow-x-auto mt-3">
                                <table className="w-full text-xs border-collapse">
                                    <thead>
                                        <tr className="text-left text-fg-muted border-b border-border">
                                            <th className="py-1 pr-2">Gene</th>
                                            <th className="py-1 pr-2">Drug / therapy</th>
                                            <th className="py-1 pr-2">Evidence</th>
                                            <th className="py-1 pr-2">Source</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {data.evidence
                                            .filter((e) => displayedDrugKeys.has(e.drug.toLowerCase()))
                                            .map((e, i) => (
                                                <tr key={i} className="border-b border-border">
                                                    <td className="py-1 pr-2 font-medium text-fg-strong">{e.gene}</td>
                                                    <td className="py-1 pr-2">
                                                        <div className="flex items-center gap-1.5">
                                                            {chartedDrugKeys.has(e.drug.toLowerCase()) && (
                                                                <span
                                                                    className="w-2 h-2 rounded-full flex-shrink-0"
                                                                    style={{ backgroundColor: drugColor[e.drug.toLowerCase()] }}
                                                                />
                                                            )}
                                                            {e.drug}
                                                        </div>
                                                    </td>
                                                    <td className="py-1 pr-2 text-fg-muted">
                                                        {e.source === 'CIViC'
                                                            ? [e.evidence_type, e.significance, e.evidence_level && `level ${e.evidence_level}`]
                                                                  .filter(Boolean)
                                                                  .join(' · ')
                                                            : [e.interaction_type, e.approved ? 'approved' : 'investigational']
                                                                  .filter(Boolean)
                                                                  .join(' · ')}
                                                    </td>
                                                    <td className="py-1 pr-2">
                                                        {e.url ? (
                                                            <a
                                                                href={e.url}
                                                                target="_blank"
                                                                rel="noopener noreferrer"
                                                                className="text-accent-fg hover:underline"
                                                            >
                                                                {e.source}
                                                            </a>
                                                        ) : (
                                                            <span className="text-fg-muted">{e.source}{e.source_db ? ` (${e.source_db})` : ''}</span>
                                                        )}
                                                    </td>
                                                </tr>
                                            ))}
                                    </tbody>
                                </table>
                            </div>

                            {excludedEvidence.length > 0 && (
                                <div className="mt-3 pt-2 border-t border-border">
                                    <p className="text-[11px] font-medium text-fg-muted mb-1">
                                        Documented resistance / adverse-response evidence (excluded from the
                                        comparison chart above, shown here for disclosure)
                                    </p>
                                    <ul className="text-[11px] text-fg-muted space-y-0.5">
                                        {excludedEvidence.map((e, i) => (
                                            <li key={i}>
                                                {e.gene} → {e.drug} — {e.significance ?? e.evidence_type}
                                                {e.url && (
                                                    <>
                                                        {' '}(<a
                                                            href={e.url}
                                                            target="_blank"
                                                            rel="noopener noreferrer"
                                                            className="text-accent-fg hover:underline"
                                                        >
                                                            {e.source}
                                                        </a>)
                                                    </>
                                                )}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}
        </div>
    )
}

export default TherapyDirections
